### ISSUE TITLE
Add Vue whitelistPatterns to purgeCss by default.

### ISSUE THREAD

**Issue by kylemilloy** [spatie/laravel-mix-purgecss#29]
Firstly, great package...thanks a lot. 

This isn't really an issue but more of a suggestion...I find myself regularly adding in the following whitelist patterns into each project that uses any Vue transition. 

```js
whitelistPatterns: [
  /-enter-active$/,
  /-leave-active$/,
  /-enter$/,
  /-leave-to$/
]
```

I know Laravel isn't married to Vue but they pretty much go hand in hand...I would suggest adding some basic whitelisting to support using vue transitions. 

Thoughts?

**Comment by sebastiandedeyne** [comment]
Nice idea! I added a set of commonly used `whitelistPatterns` in v2.1.0 :)

**Comment by kenberkeley** [comment]
```css
/* purgecss start ignore */
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s;
}
.fade-enter, .fade-leave-to {
  opacity: 0;
}
/* purgecss end ignore */
```
