### ISSUE TITLE
error with css @support for iPhoneX

### ISSUE THREAD

**Issue by bolechen** [spatie/laravel-mix-purgecss#59]
when I use 

```javascript
require('laravel-mix-purgecss');
mix.purgeCss();
```

and my css code:

```css
//for ipx
@supports (padding-bottom: constant(safe-area-inset-bottom)) or (padding-bottom: env(safe-area-inset-bottom)) {
    .app-bottom {
        // padding-bottom: 34px;
        padding-bottom: constant(safe-area-inset-bottom) !important;
        padding-bottom: env(safe-area-inset-bottom) !important;
    }
}
```

when build done,the css for iPhoneX is gone
