### ISSUE TITLE
Emitted value instead of an instance of Error

### ISSUE THREAD

**Issue by simondavies** [spatie/laravel-mix-purgecss#62]
When running in production i get the following error:

```
Module Warning (from ./node_modules/resolve-url-loader/index.js):
(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
  /Users/????/site.scss:28:11: missing '}'
  at error (/?????????????/node_modules/css/lib/parse/index.js:62:15)

 @ ./????????/site.scss 2:14-280
```
Then on investigation and to solve the error/warning I had to:

First remove all the tailwind comments within the main scss file and then put a pointless css class in there as below:

```css
@tailwind preflight;
@tailwind components;
@tailwind utilities;

 .n{display: none;}
```

Then this run as expected. So its fixed for now but not sure if it can be in the code.
